services:
  db:
    container_name: booking_db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviebooking
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    container_name: booking_backend
    build: ./Backend/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./Backend/app:/app
    working_dir: /app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviebooking
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      SECRET_KEY: supersecretkey
    ports:
      - "8000:8000"
    depends_on:
      - db

  # frontend:
  #   container_name: moviebooking_frontend
  #   build: ./Frontend
  #   volumes:
  #     - ./Frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000
  #   depends_on:
  #     - backend

volumes:
  postgres_data: 